### ISSUE TITLE
Code Inquiry

### ISSUE THREAD

**Issue by sunmu0315** [ltzheng/data-privacy-ustc#3]
Dear author, when I reproduced your code on my device recently, there was a small problem, can I ask you for advice? When I run the code in paillier mode, the GPU is NVIDIA-A100-80GB-PCIe(mig-3g.40gb):1, and the cpu is AMD EPYC 7713 64-Core Processor. However, the encryption time I run is about 630s, the decryption time is about 178s, and the overall training time is 4100s, which is 2.3 times longer than the experimental data you provided. When I run DP mode and plain mode, the experimental data is basically similar to what you provided. Why does this happen when I run Paillier? If you reply, be very grateful!

**Comment by ltzheng** [comment]
The device is mentioned in the README on line 567 as follows:

> Device: GPU clusters of School of Computer Science at USTC (with 10 Intel(R) Xeon(R) Silver 4210 CPUs and 1 Nvidia GeForce RTX 2080Ti GPU

You may want to check whether the computation is utilizing the GPU. Currently, the Paillier implementation is not parallel, but it can be optimized by implementing CUDA functions to accelerate.
